### PR TITLE
Disabling changelog uploading

### PR DESCRIPTION
**Pull request by mackoj**

### CODE REVIEW

**Comment by teriiehina** [comment]
Thank you for this PR. 

Wouldn't it be better if the changelog upload was parametrized ?

**Comment by mackoj** [comment]
Yes it's would be better

**Comment by teriiehina** [comment]
Who could do it ?

**Comment by mackoj** [comment]
Nope since I will re-implment mercure in fastlane

**Comment by mackoj** [comment]
I will do it in Fastlane directly

**Comment by teriiehina** [comment]
OK.
I will have a deeper look at fastlane when I'll do my next iOS job

**Pull request merged**
